version: '3.8'
services:
    nans-mentor-php:
        container_name: nans-mentor-php
        build:
            context: ./
            dockerfile: images/php/Dockerfile
        depends_on:
            - nans-mentor-mysql
        links:
            - nans-mentor-mysql
        ports:
            - "8080:80"
        networks:
            - bubble
        volumes:
            - ./config/apache/default.conf:/etc/apache2/sites-enabled/default.conf
            - type: bind
              source: ./src
              target: /var/www/html
    nans-mentor-mysql:
        container_name: nans-mentor-mysql
        platform: linux/x86_64
        image: mysql
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        networks:
            - bubble
        volumes:
            - ./storage/mysql:/var/lib/mysql
    nans-mentor-phpmyadmin:
        container_name: nans-mentor-phpmyadmin
        image: phpmyadmin
        ports:
            - "3305:80"
        restart: always
        environment:
            PMA_HOST: nans-mentor-mysql
            PMA_PASSWORD: ""
        depends_on:
            - nans-mentor-mysql
        networks:
            - bubble
volumes:
    src:
networks:
  bubble: